/*
 * RIXL API
 * **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@rixl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.GithubComQeeqezApiInternalVideosTypesChapterInput;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for VideosVideoIdChaptersPutRequest
 */
public class VideosVideoIdChaptersPutRequestTest {
    private final VideosVideoIdChaptersPutRequest model = new VideosVideoIdChaptersPutRequest();

    /**
     * Model tests for VideosVideoIdChaptersPutRequest
     */
    @Test
    public void testVideosVideoIdChaptersPutRequest() {
        // TODO: test VideosVideoIdChaptersPutRequest
    }

    /**
     * Test the property 'chapters'
     */
    @Test
    public void chaptersTest() {
        // TODO: test chapters
    }

}
