/*
 * RIXL API
 * **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@rixl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * InternalImagesHandlerCompleteRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-23T15:36:05.765653+01:00[Africa/Lagos]", comments = "Generator version: 7.20.0")
public class InternalImagesHandlerCompleteRequest {
  public static final String SERIALIZED_NAME_ATTACHED_TO_VIDEO = "attached_to_video";
  @SerializedName(SERIALIZED_NAME_ATTACHED_TO_VIDEO)
  @javax.annotation.Nullable
  private Boolean attachedToVideo;

  public static final String SERIALIZED_NAME_IMAGE_ID = "image_id";
  @SerializedName(SERIALIZED_NAME_IMAGE_ID)
  @javax.annotation.Nullable
  private String imageId;

  public InternalImagesHandlerCompleteRequest() {
  }

  public InternalImagesHandlerCompleteRequest attachedToVideo(@javax.annotation.Nullable Boolean attachedToVideo) {
    this.attachedToVideo = attachedToVideo;
    return this;
  }

  /**
   * Get attachedToVideo
   * @return attachedToVideo
   */
  @javax.annotation.Nullable
  public Boolean getAttachedToVideo() {
    return attachedToVideo;
  }

  public void setAttachedToVideo(@javax.annotation.Nullable Boolean attachedToVideo) {
    this.attachedToVideo = attachedToVideo;
  }


  public InternalImagesHandlerCompleteRequest imageId(@javax.annotation.Nullable String imageId) {
    this.imageId = imageId;
    return this;
  }

  /**
   * Get imageId
   * @return imageId
   */
  @javax.annotation.Nullable
  public String getImageId() {
    return imageId;
  }

  public void setImageId(@javax.annotation.Nullable String imageId) {
    this.imageId = imageId;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InternalImagesHandlerCompleteRequest internalImagesHandlerCompleteRequest = (InternalImagesHandlerCompleteRequest) o;
    return Objects.equals(this.attachedToVideo, internalImagesHandlerCompleteRequest.attachedToVideo) &&
        Objects.equals(this.imageId, internalImagesHandlerCompleteRequest.imageId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(attachedToVideo, imageId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InternalImagesHandlerCompleteRequest {\n");
    sb.append("    attachedToVideo: ").append(toIndentedString(attachedToVideo)).append("\n");
    sb.append("    imageId: ").append(toIndentedString(imageId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("attached_to_video", "image_id"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to InternalImagesHandlerCompleteRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!InternalImagesHandlerCompleteRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in InternalImagesHandlerCompleteRequest is not found in the empty JSON string", InternalImagesHandlerCompleteRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!InternalImagesHandlerCompleteRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `InternalImagesHandlerCompleteRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("image_id") != null && !jsonObj.get("image_id").isJsonNull()) && !jsonObj.get("image_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `image_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("image_id").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!InternalImagesHandlerCompleteRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'InternalImagesHandlerCompleteRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<InternalImagesHandlerCompleteRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(InternalImagesHandlerCompleteRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<InternalImagesHandlerCompleteRequest>() {
           @Override
           public void write(JsonWriter out, InternalImagesHandlerCompleteRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public InternalImagesHandlerCompleteRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of InternalImagesHandlerCompleteRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of InternalImagesHandlerCompleteRequest
   * @throws IOException if the JSON string is invalid with respect to InternalImagesHandlerCompleteRequest
   */
  public static InternalImagesHandlerCompleteRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, InternalImagesHandlerCompleteRequest.class);
  }

  /**
   * Convert an instance of InternalImagesHandlerCompleteRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

