package com.rixl.sdk.models.billing.v1;

import com.microsoft.kiota.serialization.ValuedEnum;
import java.util.Objects;

@jakarta.annotation.Generated("com.microsoft.kiota")
public enum SubscriptionStatus implements ValuedEnum {
    SUBSCRIPTION_STATUS_UNSPECIFIED("SUBSCRIPTION_STATUS_UNSPECIFIED"),
    SUBSCRIPTION_STATUS_ACTIVE("SUBSCRIPTION_STATUS_ACTIVE"),
    SUBSCRIPTION_STATUS_INACTIVE("SUBSCRIPTION_STATUS_INACTIVE"),
    SUBSCRIPTION_STATUS_CANCELED("SUBSCRIPTION_STATUS_CANCELED"),
    SUBSCRIPTION_STATUS_EXPIRED("SUBSCRIPTION_STATUS_EXPIRED"),
    SUBSCRIPTION_STATUS_PENDING("SUBSCRIPTION_STATUS_PENDING"),
    SUBSCRIPTION_STATUS_SUSPENDED("SUBSCRIPTION_STATUS_SUSPENDED"),
    SUBSCRIPTION_STATUS_TRIALING("SUBSCRIPTION_STATUS_TRIALING"),
    SUBSCRIPTION_STATUS_PAST_DUE("SUBSCRIPTION_STATUS_PAST_DUE"),
    SUBSCRIPTION_STATUS_UNPAID("SUBSCRIPTION_STATUS_UNPAID"),
    SUBSCRIPTION_STATUS_INCOMPLETE("SUBSCRIPTION_STATUS_INCOMPLETE"),
    SUBSCRIPTION_STATUS_INCOMPLETE_EXPIRED("SUBSCRIPTION_STATUS_INCOMPLETE_EXPIRED"),
    SUBSCRIPTION_STATUS_PAUSED("SUBSCRIPTION_STATUS_PAUSED");
    public final String value;
    SubscriptionStatus(final String value) {
        this.value = value;
    }
    @jakarta.annotation.Nonnull
    public String getValue() { return this.value; }
    @jakarta.annotation.Nullable
    public static SubscriptionStatus forValue(@jakarta.annotation.Nonnull final String searchValue) {
        Objects.requireNonNull(searchValue);
        switch(searchValue) {
            case "SUBSCRIPTION_STATUS_UNSPECIFIED": return SUBSCRIPTION_STATUS_UNSPECIFIED;
            case "SUBSCRIPTION_STATUS_ACTIVE": return SUBSCRIPTION_STATUS_ACTIVE;
            case "SUBSCRIPTION_STATUS_INACTIVE": return SUBSCRIPTION_STATUS_INACTIVE;
            case "SUBSCRIPTION_STATUS_CANCELED": return SUBSCRIPTION_STATUS_CANCELED;
            case "SUBSCRIPTION_STATUS_EXPIRED": return SUBSCRIPTION_STATUS_EXPIRED;
            case "SUBSCRIPTION_STATUS_PENDING": return SUBSCRIPTION_STATUS_PENDING;
            case "SUBSCRIPTION_STATUS_SUSPENDED": return SUBSCRIPTION_STATUS_SUSPENDED;
            case "SUBSCRIPTION_STATUS_TRIALING": return SUBSCRIPTION_STATUS_TRIALING;
            case "SUBSCRIPTION_STATUS_PAST_DUE": return SUBSCRIPTION_STATUS_PAST_DUE;
            case "SUBSCRIPTION_STATUS_UNPAID": return SUBSCRIPTION_STATUS_UNPAID;
            case "SUBSCRIPTION_STATUS_INCOMPLETE": return SUBSCRIPTION_STATUS_INCOMPLETE;
            case "SUBSCRIPTION_STATUS_INCOMPLETE_EXPIRED": return SUBSCRIPTION_STATUS_INCOMPLETE_EXPIRED;
            case "SUBSCRIPTION_STATUS_PAUSED": return SUBSCRIPTION_STATUS_PAUSED;
            default: return null;
        }
    }
}
