/*
 * RIXL API
 * **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@rixl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.AudioTrack;
import org.openapitools.client.model.AudioTrackDelete;
import org.openapitools.client.model.GithubComQeeqezApiInternalErrorsErrorResponse;
import org.openapitools.client.model.GithubComQeeqezApiInternalVideosHandlerUploadInitResponse;
import org.openapitools.client.model.InternalVideosHandlerSubtitlesLanguageResponse;
import org.openapitools.client.model.PaginationPaginatedResponseVideo;
import org.openapitools.client.model.Subtitle;
import org.openapitools.client.model.SubtitleDelete;
import org.openapitools.client.model.UpdateChaptersResponse;
import org.openapitools.client.model.Video;
import org.openapitools.client.model.VideosUploadCompletePostRequest;
import org.openapitools.client.model.VideosUploadInitPostRequest;
import org.openapitools.client.model.VideosVideoIdChaptersPutRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for VideosApi
 */
@Disabled
public class VideosApiTest {

    private final VideosApi api = new VideosApi();

    /**
     * List videos for a project
     *
     * Retrieve all videos for a specific project, with pagination and sorting.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void videosGetTest() throws ApiException {
        Integer limit = null;
        Integer offset = null;
        String sort = null;
        String order = null;
        PaginationPaginatedResponseVideo response = api.videosGet(limit, offset, sort, order);
        // TODO: test validations
    }

    /**
     * List available subtitle languages
     *
     * Get list of supported languages for subtitles
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void videosLanguagesGetTest() throws ApiException {
        List<InternalVideosHandlerSubtitlesLanguageResponse> response = api.videosLanguagesGet();
        // TODO: test validations
    }

    /**
     * Upload: Mark as complete
     *
     * Mark a video upload as complete after successful upload to storage using API key authentication
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void videosUploadCompletePostTest() throws ApiException {
        VideosUploadCompletePostRequest videosUploadCompletePostRequest = null;
        Video response = api.videosUploadCompletePost(videosUploadCompletePostRequest);
        // TODO: test validations
    }

    /**
     * Upload: Init
     *
     * Initialize a video upload and get presigned URLs for video and poster using API key authentication
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void videosUploadInitPostTest() throws ApiException {
        VideosUploadInitPostRequest videosUploadInitPostRequest = null;
        GithubComQeeqezApiInternalVideosHandlerUploadInitResponse response = api.videosUploadInitPost(videosUploadInitPostRequest);
        // TODO: test validations
    }

    /**
     * Delete all audio tracks
     *
     * Remove all additional audio tracks from a video using API key authentication
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void videosVideoIdAudioTracksDeleteTest() throws ApiException {
        String videoId = null;
        AudioTrackDelete response = api.videosVideoIdAudioTracksDelete(videoId);
        // TODO: test validations
    }

    /**
     * Delete audio track by language
     *
     * Remove an audio track for a specific language using API key authentication
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void videosVideoIdAudioTracksLangCodeDeleteTest() throws ApiException {
        String videoId = null;
        String langCode = null;
        AudioTrackDelete response = api.videosVideoIdAudioTracksLangCodeDelete(videoId, langCode);
        // TODO: test validations
    }

    /**
     * Upsert video audio track
     *
     * Add or replace an audio track for a specific language using API key authentication
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void videosVideoIdAudioTracksLangCodePutTest() throws ApiException {
        String videoId = null;
        String langCode = null;
        AudioTrack response = api.videosVideoIdAudioTracksLangCodePut(videoId, langCode);
        // TODO: test validations
    }

    /**
     * Bulk upsert video audio tracks
     *
     * Replace all audio tracks with the provided ones using API key authentication
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void videosVideoIdAudioTracksPostTest() throws ApiException {
        String videoId = null;
        List<AudioTrack> response = api.videosVideoIdAudioTracksPost(videoId);
        // TODO: test validations
    }

    /**
     * Delete audio track
     *
     * Remove an additional audio track from a video using API key authentication
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void videosVideoIdAudioTracksTrackIdDeleteTest() throws ApiException {
        String videoId = null;
        String trackId = null;
        AudioTrackDelete response = api.videosVideoIdAudioTracksTrackIdDelete(videoId, trackId);
        // TODO: test validations
    }

    /**
     * Delete video chapters
     *
     * Remove all chapters from a video using API key authentication
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void videosVideoIdChaptersDeleteTest() throws ApiException {
        String videoId = null;
        UpdateChaptersResponse response = api.videosVideoIdChaptersDelete(videoId);
        // TODO: test validations
    }

    /**
     * Update video chapters
     *
     * Replace all chapters for a video (atomic PUT operation) using API key authentication
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void videosVideoIdChaptersPutTest() throws ApiException {
        String videoId = null;
        VideosVideoIdChaptersPutRequest videosVideoIdChaptersPutRequest = null;
        UpdateChaptersResponse response = api.videosVideoIdChaptersPut(videoId, videosVideoIdChaptersPutRequest);
        // TODO: test validations
    }

    /**
     * Delete video
     *
     * Delete a video by its ID within a project
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void videosVideoIdDeleteDeleteTest() throws ApiException {
        String videoId = null;
        api.videosVideoIdDeleteDelete(videoId);
        // TODO: test validations
    }

    /**
     * Get a video
     *
     * Retrieve a video by its ID for a specific project.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void videosVideoIdGetTest() throws ApiException {
        String videoId = null;
        Video response = api.videosVideoIdGet(videoId);
        // TODO: test validations
    }

    /**
     * Delete all subtitles
     *
     * Remove all subtitles from a video using API key authentication
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void videosVideoIdSubtitlesDeleteTest() throws ApiException {
        String videoId = null;
        SubtitleDelete response = api.videosVideoIdSubtitlesDelete(videoId);
        // TODO: test validations
    }

    /**
     * Delete subtitle by language
     *
     * Remove a subtitle for a specific language using API key authentication
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void videosVideoIdSubtitlesLangCodeDeleteTest() throws ApiException {
        String videoId = null;
        String langCode = null;
        SubtitleDelete response = api.videosVideoIdSubtitlesLangCodeDelete(videoId, langCode);
        // TODO: test validations
    }

    /**
     * Upsert video subtitle
     *
     * Add or replace a subtitle for a specific language using API key authentication
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void videosVideoIdSubtitlesLangCodePutTest() throws ApiException {
        String videoId = null;
        String langCode = null;
        Subtitle response = api.videosVideoIdSubtitlesLangCodePut(videoId, langCode);
        // TODO: test validations
    }

    /**
     * Bulk upsert video subtitles
     *
     * Replace all subtitles with the provided ones using API key authentication
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void videosVideoIdSubtitlesPostTest() throws ApiException {
        String videoId = null;
        List<Subtitle> response = api.videosVideoIdSubtitlesPost(videoId);
        // TODO: test validations
    }

    /**
     * Delete subtitle
     *
     * Remove a subtitle from a video using API key authentication
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void videosVideoIdSubtitlesSubtitleIdDeleteTest() throws ApiException {
        String videoId = null;
        String subtitleId = null;
        SubtitleDelete response = api.videosVideoIdSubtitlesSubtitleIdDelete(videoId, subtitleId);
        // TODO: test validations
    }

    /**
     * Update video thumbnail
     *
     * Update the thumbnail image for an existing video using API key authentication
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void videosVideoIdThumbnailPutTest() throws ApiException {
        String videoId = null;
        Video response = api.videosVideoIdThumbnailPut(videoId);
        // TODO: test validations
    }

}
