/*
 * RIXL API
 * **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@rixl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.GithubComQeeqezApiInternalErrorsErrorResponse;
import org.openapitools.client.model.Image;
import org.openapitools.client.model.InternalImagesHandlerCompleteRequest;
import org.openapitools.client.model.InternalImagesHandlerInitResponse;
import org.openapitools.client.model.InternalImagesHandlerUploadInitRequest;
import org.openapitools.client.model.PaginationPaginatedResponseImage;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ImagesApi
 */
@Disabled
public class ImagesApiTest {

    private final ImagesApi api = new ImagesApi();

    /**
     * Delete image
     *
     * delete an image by marking it as deleted
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteImagesImageIdTest() throws ApiException {
        String imageId = null;
        api.deleteImagesImageId(imageId);
        // TODO: test validations
    }

    /**
     * List images for a project
     *
     * Retrieve all images for a specific project, with pagination and sorting.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getImagesTest() throws ApiException {
        Integer limit = null;
        Integer offset = null;
        String sort = null;
        String order = null;
        PaginationPaginatedResponseImage response = api.getImages(limit, offset, sort, order);
        // TODO: test validations
    }

    /**
     * Get image
     *
     * Retrieve an image by its ID for a specific project.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getImagesImageIdTest() throws ApiException {
        String imageId = null;
        Image response = api.getImagesImageId(imageId);
        // TODO: test validations
    }

    /**
     * Upload: Mark as complete
     *
     * Complete the upload process and create the image record using API key authentication
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void postImagesUploadCompleteTest() throws ApiException {
        InternalImagesHandlerCompleteRequest request = null;
        Image response = api.postImagesUploadComplete(request);
        // TODO: test validations
    }

    /**
     * Upload: Init
     *
     * Initialize a presigned URL upload for an image file using API key authentication
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void postImagesUploadInitTest() throws ApiException {
        InternalImagesHandlerUploadInitRequest request = null;
        InternalImagesHandlerInitResponse response = api.postImagesUploadInit(request);
        // TODO: test validations
    }

}
