/*
 * RIXL API
 * **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@rixl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * GithubComQeeqezApiInternalVideosTypesChapterInput
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-24T15:50:56.058816+01:00[Africa/Lagos]", comments = "Generator version: 7.20.0")
public class GithubComQeeqezApiInternalVideosTypesChapterInput {
  public static final String SERIALIZED_NAME_START_TIME_SEC = "start_time_sec";
  @SerializedName(SERIALIZED_NAME_START_TIME_SEC)
  @javax.annotation.Nullable
  private BigDecimal startTimeSec;

  public static final String SERIALIZED_NAME_TITLE = "title";
  @SerializedName(SERIALIZED_NAME_TITLE)
  @javax.annotation.Nullable
  private String title;

  public GithubComQeeqezApiInternalVideosTypesChapterInput() {
  }

  public GithubComQeeqezApiInternalVideosTypesChapterInput startTimeSec(@javax.annotation.Nullable BigDecimal startTimeSec) {
    this.startTimeSec = startTimeSec;
    return this;
  }

  /**
   * Get startTimeSec
   * @return startTimeSec
   */
  @javax.annotation.Nullable
  public BigDecimal getStartTimeSec() {
    return startTimeSec;
  }

  public void setStartTimeSec(@javax.annotation.Nullable BigDecimal startTimeSec) {
    this.startTimeSec = startTimeSec;
  }


  public GithubComQeeqezApiInternalVideosTypesChapterInput title(@javax.annotation.Nullable String title) {
    this.title = title;
    return this;
  }

  /**
   * Get title
   * @return title
   */
  @javax.annotation.Nullable
  public String getTitle() {
    return title;
  }

  public void setTitle(@javax.annotation.Nullable String title) {
    this.title = title;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GithubComQeeqezApiInternalVideosTypesChapterInput githubComQeeqezApiInternalVideosTypesChapterInput = (GithubComQeeqezApiInternalVideosTypesChapterInput) o;
    return Objects.equals(this.startTimeSec, githubComQeeqezApiInternalVideosTypesChapterInput.startTimeSec) &&
        Objects.equals(this.title, githubComQeeqezApiInternalVideosTypesChapterInput.title);
  }

  @Override
  public int hashCode() {
    return Objects.hash(startTimeSec, title);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GithubComQeeqezApiInternalVideosTypesChapterInput {\n");
    sb.append("    startTimeSec: ").append(toIndentedString(startTimeSec)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("start_time_sec", "title"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to GithubComQeeqezApiInternalVideosTypesChapterInput
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GithubComQeeqezApiInternalVideosTypesChapterInput.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in GithubComQeeqezApiInternalVideosTypesChapterInput is not found in the empty JSON string", GithubComQeeqezApiInternalVideosTypesChapterInput.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!GithubComQeeqezApiInternalVideosTypesChapterInput.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `GithubComQeeqezApiInternalVideosTypesChapterInput` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("title") != null && !jsonObj.get("title").isJsonNull()) && !jsonObj.get("title").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `title` to be a primitive type in the JSON string but got `%s`", jsonObj.get("title").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GithubComQeeqezApiInternalVideosTypesChapterInput.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GithubComQeeqezApiInternalVideosTypesChapterInput' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GithubComQeeqezApiInternalVideosTypesChapterInput> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GithubComQeeqezApiInternalVideosTypesChapterInput.class));

       return (TypeAdapter<T>) new TypeAdapter<GithubComQeeqezApiInternalVideosTypesChapterInput>() {
           @Override
           public void write(JsonWriter out, GithubComQeeqezApiInternalVideosTypesChapterInput value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GithubComQeeqezApiInternalVideosTypesChapterInput read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of GithubComQeeqezApiInternalVideosTypesChapterInput given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GithubComQeeqezApiInternalVideosTypesChapterInput
   * @throws IOException if the JSON string is invalid with respect to GithubComQeeqezApiInternalVideosTypesChapterInput
   */
  public static GithubComQeeqezApiInternalVideosTypesChapterInput fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GithubComQeeqezApiInternalVideosTypesChapterInput.class);
  }

  /**
   * Convert an instance of GithubComQeeqezApiInternalVideosTypesChapterInput to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

