/*
 * RIXL API
 * **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@rixl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;



import java.io.IOException;
import java.lang.reflect.Type;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.JsonPrimitive;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonSerializationContext;
import com.google.gson.JsonSerializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonArray;
import com.google.gson.JsonParseException;

import org.openapitools.client.JSON;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-24T15:50:56.058816+01:00[Africa/Lagos]", comments = "Generator version: 7.20.0")
public class ImagesUploadInitPostRequest extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(ImagesUploadInitPostRequest.class.getName());

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!ImagesUploadInitPostRequest.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'ImagesUploadInitPostRequest' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<Object> adapterObject = gson.getDelegateAdapter(this, TypeToken.get(Object.class));
            final TypeAdapter<InternalImagesHandlerUploadInitRequest> adapterInternalImagesHandlerUploadInitRequest = gson.getDelegateAdapter(this, TypeToken.get(InternalImagesHandlerUploadInitRequest.class));

            return (TypeAdapter<T>) new TypeAdapter<ImagesUploadInitPostRequest>() {
                @Override
                public void write(JsonWriter out, ImagesUploadInitPostRequest value) throws IOException {
                    if (value == null || value.getActualInstance() == null) {
                        elementAdapter.write(out, null);
                        return;
                    }

                    // check if the actual instance is of the type `Object`
                    if (value.getActualInstance() instanceof Object) {
                        JsonPrimitive primitive = adapterObject.toJsonTree((Object)value.getActualInstance()).getAsJsonPrimitive();
                        elementAdapter.write(out, primitive);
                        return;
                    }
                    // check if the actual instance is of the type `InternalImagesHandlerUploadInitRequest`
                    if (value.getActualInstance() instanceof InternalImagesHandlerUploadInitRequest) {
                        JsonElement element = adapterInternalImagesHandlerUploadInitRequest.toJsonTree((InternalImagesHandlerUploadInitRequest)value.getActualInstance());
                        elementAdapter.write(out, element);
                        return;
                    }
                    throw new IOException("Failed to serialize as the type doesn't match oneOf schemas: InternalImagesHandlerUploadInitRequest, Object");
                }

                @Override
                public ImagesUploadInitPostRequest read(JsonReader in) throws IOException {
                    Object deserialized = null;
                    JsonElement jsonElement = elementAdapter.read(in);

                    int match = 0;
                    ArrayList<String> errorMessages = new ArrayList<>();
                    TypeAdapter actualAdapter = elementAdapter;

                    // deserialize Object
                    try {
                        // validate the JSON object to see if any exception is thrown
                        if (!jsonElement.getAsJsonPrimitive().isNumber()) {
                            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected json element to be of type Number in the JSON string but got `%s`", jsonElement.toString()));
                        }
                        actualAdapter = adapterObject;
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'Object'");
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format(java.util.Locale.ROOT, "Deserialization for Object failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'Object'", e);
                    }
                    // deserialize InternalImagesHandlerUploadInitRequest
                    try {
                        // validate the JSON object to see if any exception is thrown
                        InternalImagesHandlerUploadInitRequest.validateJsonElement(jsonElement);
                        actualAdapter = adapterInternalImagesHandlerUploadInitRequest;
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'InternalImagesHandlerUploadInitRequest'");
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format(java.util.Locale.ROOT, "Deserialization for InternalImagesHandlerUploadInitRequest failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'InternalImagesHandlerUploadInitRequest'", e);
                    }

                    if (match == 1) {
                        ImagesUploadInitPostRequest ret = new ImagesUploadInitPostRequest();
                        ret.setActualInstance(actualAdapter.fromJsonTree(jsonElement));
                        return ret;
                    }

                    throw new IOException(String.format(java.util.Locale.ROOT, "Failed deserialization for ImagesUploadInitPostRequest: %d classes match result, expected 1. Detailed failure message for oneOf schemas: %s. JSON: %s", match, errorMessages, jsonElement.toString()));
                }
            }.nullSafe();
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, Class<?>> schemas = new HashMap<String, Class<?>>();

    public ImagesUploadInitPostRequest() {
        super("oneOf", Boolean.FALSE);
    }

    public ImagesUploadInitPostRequest(Object o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("Object", Object.class);
        schemas.put("InternalImagesHandlerUploadInitRequest", InternalImagesHandlerUploadInitRequest.class);
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return ImagesUploadInitPostRequest.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * InternalImagesHandlerUploadInitRequest, Object
     *
     * It could be an instance of the 'oneOf' schemas.
     */
    @Override
    public void setActualInstance(Object instance) {
        if (instance instanceof Object) {
            super.setActualInstance(instance);
            return;
        }

        if (instance instanceof InternalImagesHandlerUploadInitRequest) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be InternalImagesHandlerUploadInitRequest, Object");
    }

    /**
     * Get the actual instance, which can be the following:
     * InternalImagesHandlerUploadInitRequest, Object
     *
     * @return The actual instance (InternalImagesHandlerUploadInitRequest, Object)
     */
    @SuppressWarnings("unchecked")
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `Object`. If the actual instance is not `Object`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `Object`
     * @throws ClassCastException if the instance is not `Object`
     */
    public Object getObject() throws ClassCastException {
        return (Object)super.getActualInstance();
    }

    /**
     * Get the actual instance of `InternalImagesHandlerUploadInitRequest`. If the actual instance is not `InternalImagesHandlerUploadInitRequest`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `InternalImagesHandlerUploadInitRequest`
     * @throws ClassCastException if the instance is not `InternalImagesHandlerUploadInitRequest`
     */
    public InternalImagesHandlerUploadInitRequest getInternalImagesHandlerUploadInitRequest() throws ClassCastException {
        return (InternalImagesHandlerUploadInitRequest)super.getActualInstance();
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to ImagesUploadInitPostRequest
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        // validate oneOf schemas one by one
        int validCount = 0;
        ArrayList<String> errorMessages = new ArrayList<>();
        // validate the json string with Object
        try {
            if (!jsonElement.getAsJsonPrimitive().isNumber()) {
                throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected json element to be of type Number in the JSON string but got `%s`", jsonElement.toString()));
            }
            validCount++;
        } catch (Exception e) {
            errorMessages.add(String.format(java.util.Locale.ROOT, "Deserialization for Object failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        // validate the json string with InternalImagesHandlerUploadInitRequest
        try {
            InternalImagesHandlerUploadInitRequest.validateJsonElement(jsonElement);
            validCount++;
        } catch (Exception e) {
            errorMessages.add(String.format(java.util.Locale.ROOT, "Deserialization for InternalImagesHandlerUploadInitRequest failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        if (validCount != 1) {
            throw new IOException(String.format(java.util.Locale.ROOT, "The JSON string is invalid for ImagesUploadInitPostRequest with oneOf schemas: InternalImagesHandlerUploadInitRequest, Object. %d class(es) match the result, expected 1. Detailed failure message for oneOf schemas: %s. JSON: %s", validCount, errorMessages, jsonElement.toString()));
        }
    }

    /**
     * Create an instance of ImagesUploadInitPostRequest given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of ImagesUploadInitPostRequest
     * @throws IOException if the JSON string is invalid with respect to ImagesUploadInitPostRequest
     */
    public static ImagesUploadInitPostRequest fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, ImagesUploadInitPostRequest.class);
    }

    /**
     * Convert an instance of ImagesUploadInitPostRequest to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}

