/*
 * RIXL API
 * **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@rixl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * InternalImagesHandlerInitResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-24T15:50:56.058816+01:00[Africa/Lagos]", comments = "Generator version: 7.20.0")
public class InternalImagesHandlerInitResponse {
  public static final String SERIALIZED_NAME_IMAGE_ID = "image_id";
  @SerializedName(SERIALIZED_NAME_IMAGE_ID)
  @javax.annotation.Nullable
  private String imageId;

  public static final String SERIALIZED_NAME_PRESIGNED_URL = "presigned_url";
  @SerializedName(SERIALIZED_NAME_PRESIGNED_URL)
  @javax.annotation.Nullable
  private String presignedUrl;

  public static final String SERIALIZED_NAME_UPLOAD_EXPIRES = "upload_expires";
  @SerializedName(SERIALIZED_NAME_UPLOAD_EXPIRES)
  @javax.annotation.Nullable
  private Integer uploadExpires;

  public InternalImagesHandlerInitResponse() {
  }

  public InternalImagesHandlerInitResponse imageId(@javax.annotation.Nullable String imageId) {
    this.imageId = imageId;
    return this;
  }

  /**
   * Get imageId
   * @return imageId
   */
  @javax.annotation.Nullable
  public String getImageId() {
    return imageId;
  }

  public void setImageId(@javax.annotation.Nullable String imageId) {
    this.imageId = imageId;
  }


  public InternalImagesHandlerInitResponse presignedUrl(@javax.annotation.Nullable String presignedUrl) {
    this.presignedUrl = presignedUrl;
    return this;
  }

  /**
   * Get presignedUrl
   * @return presignedUrl
   */
  @javax.annotation.Nullable
  public String getPresignedUrl() {
    return presignedUrl;
  }

  public void setPresignedUrl(@javax.annotation.Nullable String presignedUrl) {
    this.presignedUrl = presignedUrl;
  }


  public InternalImagesHandlerInitResponse uploadExpires(@javax.annotation.Nullable Integer uploadExpires) {
    this.uploadExpires = uploadExpires;
    return this;
  }

  /**
   * Get uploadExpires
   * @return uploadExpires
   */
  @javax.annotation.Nullable
  public Integer getUploadExpires() {
    return uploadExpires;
  }

  public void setUploadExpires(@javax.annotation.Nullable Integer uploadExpires) {
    this.uploadExpires = uploadExpires;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InternalImagesHandlerInitResponse internalImagesHandlerInitResponse = (InternalImagesHandlerInitResponse) o;
    return Objects.equals(this.imageId, internalImagesHandlerInitResponse.imageId) &&
        Objects.equals(this.presignedUrl, internalImagesHandlerInitResponse.presignedUrl) &&
        Objects.equals(this.uploadExpires, internalImagesHandlerInitResponse.uploadExpires);
  }

  @Override
  public int hashCode() {
    return Objects.hash(imageId, presignedUrl, uploadExpires);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InternalImagesHandlerInitResponse {\n");
    sb.append("    imageId: ").append(toIndentedString(imageId)).append("\n");
    sb.append("    presignedUrl: ").append(toIndentedString(presignedUrl)).append("\n");
    sb.append("    uploadExpires: ").append(toIndentedString(uploadExpires)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("image_id", "presigned_url", "upload_expires"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to InternalImagesHandlerInitResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!InternalImagesHandlerInitResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in InternalImagesHandlerInitResponse is not found in the empty JSON string", InternalImagesHandlerInitResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!InternalImagesHandlerInitResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `InternalImagesHandlerInitResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("image_id") != null && !jsonObj.get("image_id").isJsonNull()) && !jsonObj.get("image_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `image_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("image_id").toString()));
      }
      if ((jsonObj.get("presigned_url") != null && !jsonObj.get("presigned_url").isJsonNull()) && !jsonObj.get("presigned_url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `presigned_url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("presigned_url").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!InternalImagesHandlerInitResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'InternalImagesHandlerInitResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<InternalImagesHandlerInitResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(InternalImagesHandlerInitResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<InternalImagesHandlerInitResponse>() {
           @Override
           public void write(JsonWriter out, InternalImagesHandlerInitResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public InternalImagesHandlerInitResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of InternalImagesHandlerInitResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of InternalImagesHandlerInitResponse
   * @throws IOException if the JSON string is invalid with respect to InternalImagesHandlerInitResponse
   */
  public static InternalImagesHandlerInitResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, InternalImagesHandlerInitResponse.class);
  }

  /**
   * Convert an instance of InternalImagesHandlerInitResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

