/*
 * RIXL API
 * **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@rixl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.GithubComQeeqezApiInternalErrorsErrorResponse;
import org.openapitools.client.model.PaginationPaginatedResponsePost;
import org.openapitools.client.model.Post;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for FeedsApi
 */
@Disabled
public class FeedsApiTest {

    private final FeedsApi api = new FeedsApi();

    /**
     * List posts in a feed
     *
     * Retrieve posts in a feed, with pagination.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getFeedsFeedIdTest() throws ApiException {
        String feedId = null;
        Integer limit = null;
        Integer offset = null;
        PaginationPaginatedResponsePost response = api.getFeedsFeedId(feedId, limit, offset);
        // TODO: test validations
    }

    /**
     * List posts by creator
     *
     * Retrieve posts in a feed by a specific creator, with pagination.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getFeedsFeedIdCreatorsCreatorIdTest() throws ApiException {
        String feedId = null;
        String creatorId = null;
        Integer limit = null;
        Integer offset = null;
        PaginationPaginatedResponsePost response = api.getFeedsFeedIdCreatorsCreatorId(feedId, creatorId, limit, offset);
        // TODO: test validations
    }

    /**
     * Get a post
     *
     * Retrieve a post from feed by its ID
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getFeedsFeedIdPostIdTest() throws ApiException {
        String feedId = null;
        String postId = null;
        Post response = api.getFeedsFeedIdPostId(feedId, postId);
        // TODO: test validations
    }

}
