/*
 * RIXL API
 * **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@rixl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.rixl.sdk.feeds.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * GithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest
 */
@JsonPropertyOrder({
  GithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest.JSON_PROPERTY_VIDEO_ID
})
@JsonTypeName("github_com_qeeqez_api_internal_videos_handler_upload.CompleteRequest")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-23T11:10:31.860620+01:00[Africa/Lagos]", comments = "Generator version: 7.20.0")
public class GithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest {
  public static final String JSON_PROPERTY_VIDEO_ID = "video_id";
  @javax.annotation.Nullable
  private String videoId;

  public GithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest() {
  }

  public GithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest videoId(@javax.annotation.Nullable String videoId) {
    
    this.videoId = videoId;
    return this;
  }

  /**
   * Get videoId
   * @return videoId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VIDEO_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getVideoId() {
    return videoId;
  }


  @JsonProperty(value = JSON_PROPERTY_VIDEO_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVideoId(@javax.annotation.Nullable String videoId) {
    this.videoId = videoId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest githubComQeeqezApiInternalVideosHandlerUploadCompleteRequest = (GithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest) o;
    return Objects.equals(this.videoId, githubComQeeqezApiInternalVideosHandlerUploadCompleteRequest.videoId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(videoId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GithubComQeeqezApiInternalVideosHandlerUploadCompleteRequest {\n");
    sb.append("    videoId: ").append(toIndentedString(videoId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

