/*
 * RIXL API
 * **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@rixl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.Chapter;
import org.openapitools.client.model.GithubComQeeqezApiDbSqlcPlanType;
import org.openapitools.client.model.Image;
import org.openapitools.client.model.ModelFile;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GithubComQeeqezApiInternalVideosVideoResponse
 */
public class GithubComQeeqezApiInternalVideosVideoResponseTest {
    private final GithubComQeeqezApiInternalVideosVideoResponse model = new GithubComQeeqezApiInternalVideosVideoResponse();

    /**
     * Model tests for GithubComQeeqezApiInternalVideosVideoResponse
     */
    @Test
    public void testGithubComQeeqezApiInternalVideosVideoResponse() {
        // TODO: test GithubComQeeqezApiInternalVideosVideoResponse
    }

    /**
     * Test the property 'bitrate'
     */
    @Test
    public void bitrateTest() {
        // TODO: test bitrate
    }

    /**
     * Test the property 'chapters'
     */
    @Test
    public void chaptersTest() {
        // TODO: test chapters
    }

    /**
     * Test the property 'codec'
     */
    @Test
    public void codecTest() {
        // TODO: test codec
    }

    /**
     * Test the property 'duration'
     */
    @Test
    public void durationTest() {
        // TODO: test duration
    }

    /**
     * Test the property '_file'
     */
    @Test
    public void _fileTest() {
        // TODO: test _file
    }

    /**
     * Test the property 'framerate'
     */
    @Test
    public void framerateTest() {
        // TODO: test framerate
    }

    /**
     * Test the property 'hdr'
     */
    @Test
    public void hdrTest() {
        // TODO: test hdr
    }

    /**
     * Test the property 'height'
     */
    @Test
    public void heightTest() {
        // TODO: test height
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'planType'
     */
    @Test
    public void planTypeTest() {
        // TODO: test planType
    }

    /**
     * Test the property 'poster'
     */
    @Test
    public void posterTest() {
        // TODO: test poster
    }

    /**
     * Test the property 'width'
     */
    @Test
    public void widthTest() {
        // TODO: test width
    }

}
