/*
 * RIXL API
 * **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@rixl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets github_com_qeeqez_api_db_sqlc.VideoQuality
 */
@JsonAdapter(GithubComQeeqezApiDbSqlcVideoQuality.Adapter.class)
public enum GithubComQeeqezApiDbSqlcVideoQuality {
  
  VideoQualityBasic("basic"),
  
  VideoQualityShorts("shorts"),
  
  VideoQualityPro("pro");

  private String value;

  GithubComQeeqezApiDbSqlcVideoQuality(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static GithubComQeeqezApiDbSqlcVideoQuality fromValue(String value) {
    for (GithubComQeeqezApiDbSqlcVideoQuality b : GithubComQeeqezApiDbSqlcVideoQuality.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<GithubComQeeqezApiDbSqlcVideoQuality> {
    @Override
    public void write(final JsonWriter jsonWriter, final GithubComQeeqezApiDbSqlcVideoQuality enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public GithubComQeeqezApiDbSqlcVideoQuality read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return GithubComQeeqezApiDbSqlcVideoQuality.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    GithubComQeeqezApiDbSqlcVideoQuality.fromValue(value);
  }
}

