/*
 * RIXL API
 * **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@rixl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * GithubComQeeqezApiInternalVideosHandlerUploadInitResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-23T15:36:03.624876+01:00[Africa/Lagos]", comments = "Generator version: 7.20.0")
public class GithubComQeeqezApiInternalVideosHandlerUploadInitResponse {
  public static final String SERIALIZED_NAME_POSTER_ID = "poster_id";
  @SerializedName(SERIALIZED_NAME_POSTER_ID)
  @javax.annotation.Nullable
  private String posterId;

  public static final String SERIALIZED_NAME_POSTER_PRESIGNED_URL = "poster_presigned_url";
  @SerializedName(SERIALIZED_NAME_POSTER_PRESIGNED_URL)
  @javax.annotation.Nullable
  private String posterPresignedUrl;

  public static final String SERIALIZED_NAME_UPLOAD_EXPIRES = "upload_expires";
  @SerializedName(SERIALIZED_NAME_UPLOAD_EXPIRES)
  @javax.annotation.Nullable
  private Integer uploadExpires;

  public static final String SERIALIZED_NAME_VIDEO_ID = "video_id";
  @SerializedName(SERIALIZED_NAME_VIDEO_ID)
  @javax.annotation.Nullable
  private String videoId;

  public static final String SERIALIZED_NAME_VIDEO_PRESIGNED_URL = "video_presigned_url";
  @SerializedName(SERIALIZED_NAME_VIDEO_PRESIGNED_URL)
  @javax.annotation.Nullable
  private String videoPresignedUrl;

  public GithubComQeeqezApiInternalVideosHandlerUploadInitResponse() {
  }

  public GithubComQeeqezApiInternalVideosHandlerUploadInitResponse posterId(@javax.annotation.Nullable String posterId) {
    this.posterId = posterId;
    return this;
  }

  /**
   * Get posterId
   * @return posterId
   */
  @javax.annotation.Nullable
  public String getPosterId() {
    return posterId;
  }

  public void setPosterId(@javax.annotation.Nullable String posterId) {
    this.posterId = posterId;
  }


  public GithubComQeeqezApiInternalVideosHandlerUploadInitResponse posterPresignedUrl(@javax.annotation.Nullable String posterPresignedUrl) {
    this.posterPresignedUrl = posterPresignedUrl;
    return this;
  }

  /**
   * Get posterPresignedUrl
   * @return posterPresignedUrl
   */
  @javax.annotation.Nullable
  public String getPosterPresignedUrl() {
    return posterPresignedUrl;
  }

  public void setPosterPresignedUrl(@javax.annotation.Nullable String posterPresignedUrl) {
    this.posterPresignedUrl = posterPresignedUrl;
  }


  public GithubComQeeqezApiInternalVideosHandlerUploadInitResponse uploadExpires(@javax.annotation.Nullable Integer uploadExpires) {
    this.uploadExpires = uploadExpires;
    return this;
  }

  /**
   * Get uploadExpires
   * @return uploadExpires
   */
  @javax.annotation.Nullable
  public Integer getUploadExpires() {
    return uploadExpires;
  }

  public void setUploadExpires(@javax.annotation.Nullable Integer uploadExpires) {
    this.uploadExpires = uploadExpires;
  }


  public GithubComQeeqezApiInternalVideosHandlerUploadInitResponse videoId(@javax.annotation.Nullable String videoId) {
    this.videoId = videoId;
    return this;
  }

  /**
   * Get videoId
   * @return videoId
   */
  @javax.annotation.Nullable
  public String getVideoId() {
    return videoId;
  }

  public void setVideoId(@javax.annotation.Nullable String videoId) {
    this.videoId = videoId;
  }


  public GithubComQeeqezApiInternalVideosHandlerUploadInitResponse videoPresignedUrl(@javax.annotation.Nullable String videoPresignedUrl) {
    this.videoPresignedUrl = videoPresignedUrl;
    return this;
  }

  /**
   * Get videoPresignedUrl
   * @return videoPresignedUrl
   */
  @javax.annotation.Nullable
  public String getVideoPresignedUrl() {
    return videoPresignedUrl;
  }

  public void setVideoPresignedUrl(@javax.annotation.Nullable String videoPresignedUrl) {
    this.videoPresignedUrl = videoPresignedUrl;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GithubComQeeqezApiInternalVideosHandlerUploadInitResponse githubComQeeqezApiInternalVideosHandlerUploadInitResponse = (GithubComQeeqezApiInternalVideosHandlerUploadInitResponse) o;
    return Objects.equals(this.posterId, githubComQeeqezApiInternalVideosHandlerUploadInitResponse.posterId) &&
        Objects.equals(this.posterPresignedUrl, githubComQeeqezApiInternalVideosHandlerUploadInitResponse.posterPresignedUrl) &&
        Objects.equals(this.uploadExpires, githubComQeeqezApiInternalVideosHandlerUploadInitResponse.uploadExpires) &&
        Objects.equals(this.videoId, githubComQeeqezApiInternalVideosHandlerUploadInitResponse.videoId) &&
        Objects.equals(this.videoPresignedUrl, githubComQeeqezApiInternalVideosHandlerUploadInitResponse.videoPresignedUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(posterId, posterPresignedUrl, uploadExpires, videoId, videoPresignedUrl);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GithubComQeeqezApiInternalVideosHandlerUploadInitResponse {\n");
    sb.append("    posterId: ").append(toIndentedString(posterId)).append("\n");
    sb.append("    posterPresignedUrl: ").append(toIndentedString(posterPresignedUrl)).append("\n");
    sb.append("    uploadExpires: ").append(toIndentedString(uploadExpires)).append("\n");
    sb.append("    videoId: ").append(toIndentedString(videoId)).append("\n");
    sb.append("    videoPresignedUrl: ").append(toIndentedString(videoPresignedUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("poster_id", "poster_presigned_url", "upload_expires", "video_id", "video_presigned_url"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to GithubComQeeqezApiInternalVideosHandlerUploadInitResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GithubComQeeqezApiInternalVideosHandlerUploadInitResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in GithubComQeeqezApiInternalVideosHandlerUploadInitResponse is not found in the empty JSON string", GithubComQeeqezApiInternalVideosHandlerUploadInitResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!GithubComQeeqezApiInternalVideosHandlerUploadInitResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `GithubComQeeqezApiInternalVideosHandlerUploadInitResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("poster_id") != null && !jsonObj.get("poster_id").isJsonNull()) && !jsonObj.get("poster_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `poster_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("poster_id").toString()));
      }
      if ((jsonObj.get("poster_presigned_url") != null && !jsonObj.get("poster_presigned_url").isJsonNull()) && !jsonObj.get("poster_presigned_url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `poster_presigned_url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("poster_presigned_url").toString()));
      }
      if ((jsonObj.get("video_id") != null && !jsonObj.get("video_id").isJsonNull()) && !jsonObj.get("video_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `video_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("video_id").toString()));
      }
      if ((jsonObj.get("video_presigned_url") != null && !jsonObj.get("video_presigned_url").isJsonNull()) && !jsonObj.get("video_presigned_url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `video_presigned_url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("video_presigned_url").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GithubComQeeqezApiInternalVideosHandlerUploadInitResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GithubComQeeqezApiInternalVideosHandlerUploadInitResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GithubComQeeqezApiInternalVideosHandlerUploadInitResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GithubComQeeqezApiInternalVideosHandlerUploadInitResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<GithubComQeeqezApiInternalVideosHandlerUploadInitResponse>() {
           @Override
           public void write(JsonWriter out, GithubComQeeqezApiInternalVideosHandlerUploadInitResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GithubComQeeqezApiInternalVideosHandlerUploadInitResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of GithubComQeeqezApiInternalVideosHandlerUploadInitResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GithubComQeeqezApiInternalVideosHandlerUploadInitResponse
   * @throws IOException if the JSON string is invalid with respect to GithubComQeeqezApiInternalVideosHandlerUploadInitResponse
   */
  public static GithubComQeeqezApiInternalVideosHandlerUploadInitResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GithubComQeeqezApiInternalVideosHandlerUploadInitResponse.class);
  }

  /**
   * Convert an instance of GithubComQeeqezApiInternalVideosHandlerUploadInitResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

