/*
 * RIXL API
 * **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@rixl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.GithubComQeeqezApiInternalVideosTypesChapterInput;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * UpdateChaptersRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-23T17:28:35.758920+01:00[Africa/Lagos]", comments = "Generator version: 7.20.0")
public class UpdateChaptersRequest {
  public static final String SERIALIZED_NAME_CHAPTERS = "chapters";
  @SerializedName(SERIALIZED_NAME_CHAPTERS)
  @javax.annotation.Nullable
  private List<GithubComQeeqezApiInternalVideosTypesChapterInput> chapters = new ArrayList<>();

  public UpdateChaptersRequest() {
  }

  public UpdateChaptersRequest chapters(@javax.annotation.Nullable List<GithubComQeeqezApiInternalVideosTypesChapterInput> chapters) {
    this.chapters = chapters;
    return this;
  }

  public UpdateChaptersRequest addChaptersItem(GithubComQeeqezApiInternalVideosTypesChapterInput chaptersItem) {
    if (this.chapters == null) {
      this.chapters = new ArrayList<>();
    }
    this.chapters.add(chaptersItem);
    return this;
  }

  /**
   * Get chapters
   * @return chapters
   */
  @javax.annotation.Nullable
  public List<GithubComQeeqezApiInternalVideosTypesChapterInput> getChapters() {
    return chapters;
  }

  public void setChapters(@javax.annotation.Nullable List<GithubComQeeqezApiInternalVideosTypesChapterInput> chapters) {
    this.chapters = chapters;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateChaptersRequest updateChaptersRequest = (UpdateChaptersRequest) o;
    return Objects.equals(this.chapters, updateChaptersRequest.chapters);
  }

  @Override
  public int hashCode() {
    return Objects.hash(chapters);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateChaptersRequest {\n");
    sb.append("    chapters: ").append(toIndentedString(chapters)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("chapters"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to UpdateChaptersRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!UpdateChaptersRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in UpdateChaptersRequest is not found in the empty JSON string", UpdateChaptersRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!UpdateChaptersRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `UpdateChaptersRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("chapters") != null && !jsonObj.get("chapters").isJsonNull()) {
        JsonArray jsonArraychapters = jsonObj.getAsJsonArray("chapters");
        if (jsonArraychapters != null) {
          // ensure the json data is an array
          if (!jsonObj.get("chapters").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `chapters` to be an array in the JSON string but got `%s`", jsonObj.get("chapters").toString()));
          }

          // validate the optional field `chapters` (array)
          for (int i = 0; i < jsonArraychapters.size(); i++) {
            GithubComQeeqezApiInternalVideosTypesChapterInput.validateJsonElement(jsonArraychapters.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!UpdateChaptersRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'UpdateChaptersRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<UpdateChaptersRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(UpdateChaptersRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<UpdateChaptersRequest>() {
           @Override
           public void write(JsonWriter out, UpdateChaptersRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public UpdateChaptersRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of UpdateChaptersRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of UpdateChaptersRequest
   * @throws IOException if the JSON string is invalid with respect to UpdateChaptersRequest
   */
  public static UpdateChaptersRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, UpdateChaptersRequest.class);
  }

  /**
   * Convert an instance of UpdateChaptersRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

