/*
 * RIXL API
 * **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@rixl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.rixl.sdk.videos.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Chapter
 */
@JsonPropertyOrder({
  Chapter.JSON_PROPERTY_DURATION_LABEL,
  Chapter.JSON_PROPERTY_END_TIME_SEC,
  Chapter.JSON_PROPERTY_START_TIME_SEC,
  Chapter.JSON_PROPERTY_TITLE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-23T11:10:33.968578+01:00[Africa/Lagos]", comments = "Generator version: 7.20.0")
public class Chapter {
  public static final String JSON_PROPERTY_DURATION_LABEL = "duration_label";
  @javax.annotation.Nullable
  private String durationLabel;

  public static final String JSON_PROPERTY_END_TIME_SEC = "end_time_sec";
  @javax.annotation.Nullable
  private BigDecimal endTimeSec;

  public static final String JSON_PROPERTY_START_TIME_SEC = "start_time_sec";
  @javax.annotation.Nullable
  private BigDecimal startTimeSec;

  public static final String JSON_PROPERTY_TITLE = "title";
  @javax.annotation.Nullable
  private String title;

  public Chapter() {
  }

  public Chapter durationLabel(@javax.annotation.Nullable String durationLabel) {
    
    this.durationLabel = durationLabel;
    return this;
  }

  /**
   * Get durationLabel
   * @return durationLabel
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DURATION_LABEL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDurationLabel() {
    return durationLabel;
  }


  @JsonProperty(value = JSON_PROPERTY_DURATION_LABEL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDurationLabel(@javax.annotation.Nullable String durationLabel) {
    this.durationLabel = durationLabel;
  }

  public Chapter endTimeSec(@javax.annotation.Nullable BigDecimal endTimeSec) {
    
    this.endTimeSec = endTimeSec;
    return this;
  }

  /**
   * Get endTimeSec
   * @return endTimeSec
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_END_TIME_SEC, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getEndTimeSec() {
    return endTimeSec;
  }


  @JsonProperty(value = JSON_PROPERTY_END_TIME_SEC, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEndTimeSec(@javax.annotation.Nullable BigDecimal endTimeSec) {
    this.endTimeSec = endTimeSec;
  }

  public Chapter startTimeSec(@javax.annotation.Nullable BigDecimal startTimeSec) {
    
    this.startTimeSec = startTimeSec;
    return this;
  }

  /**
   * Get startTimeSec
   * @return startTimeSec
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_START_TIME_SEC, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getStartTimeSec() {
    return startTimeSec;
  }


  @JsonProperty(value = JSON_PROPERTY_START_TIME_SEC, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStartTimeSec(@javax.annotation.Nullable BigDecimal startTimeSec) {
    this.startTimeSec = startTimeSec;
  }

  public Chapter title(@javax.annotation.Nullable String title) {
    
    this.title = title;
    return this;
  }

  /**
   * Get title
   * @return title
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TITLE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTitle() {
    return title;
  }


  @JsonProperty(value = JSON_PROPERTY_TITLE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTitle(@javax.annotation.Nullable String title) {
    this.title = title;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Chapter chapter = (Chapter) o;
    return Objects.equals(this.durationLabel, chapter.durationLabel) &&
        Objects.equals(this.endTimeSec, chapter.endTimeSec) &&
        Objects.equals(this.startTimeSec, chapter.startTimeSec) &&
        Objects.equals(this.title, chapter.title);
  }

  @Override
  public int hashCode() {
    return Objects.hash(durationLabel, endTimeSec, startTimeSec, title);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Chapter {\n");
    sb.append("    durationLabel: ").append(toIndentedString(durationLabel)).append("\n");
    sb.append("    endTimeSec: ").append(toIndentedString(endTimeSec)).append("\n");
    sb.append("    startTimeSec: ").append(toIndentedString(startTimeSec)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

