/*
 * RIXL API
 * **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@rixl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.rixl.sdk.videos.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Gets or Sets github_com_qeeqez_api_db_sqlc.PlanType
 */
public enum GithubComQeeqezApiDbSqlcPlanType {
  
  PlanTypeFree("free"),
  
  PlanTypePro("pro"),
  
  PlanTypeCustom("custom"),
  
  PlanTypePayAsYouGo("pay_as_you_go");

  private String value;

  GithubComQeeqezApiDbSqlcPlanType(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static GithubComQeeqezApiDbSqlcPlanType fromValue(String value) {
    for (GithubComQeeqezApiDbSqlcPlanType b : GithubComQeeqezApiDbSqlcPlanType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}

