/*
 * RIXL API
 * **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@rixl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.rixl.sdk.videos.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * GithubComQeeqezApiInternalVideosHandlerUploadInitResponse
 */
@JsonPropertyOrder({
  GithubComQeeqezApiInternalVideosHandlerUploadInitResponse.JSON_PROPERTY_POSTER_ID,
  GithubComQeeqezApiInternalVideosHandlerUploadInitResponse.JSON_PROPERTY_POSTER_PRESIGNED_URL,
  GithubComQeeqezApiInternalVideosHandlerUploadInitResponse.JSON_PROPERTY_UPLOAD_EXPIRES,
  GithubComQeeqezApiInternalVideosHandlerUploadInitResponse.JSON_PROPERTY_VIDEO_ID,
  GithubComQeeqezApiInternalVideosHandlerUploadInitResponse.JSON_PROPERTY_VIDEO_PRESIGNED_URL
})
@JsonTypeName("github_com_qeeqez_api_internal_videos_handler_upload.InitResponse")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.20.0")
public class GithubComQeeqezApiInternalVideosHandlerUploadInitResponse {
  public static final String JSON_PROPERTY_POSTER_ID = "poster_id";
  @javax.annotation.Nullable
  private String posterId;

  public static final String JSON_PROPERTY_POSTER_PRESIGNED_URL = "poster_presigned_url";
  @javax.annotation.Nullable
  private String posterPresignedUrl;

  public static final String JSON_PROPERTY_UPLOAD_EXPIRES = "upload_expires";
  @javax.annotation.Nullable
  private Integer uploadExpires;

  public static final String JSON_PROPERTY_VIDEO_ID = "video_id";
  @javax.annotation.Nullable
  private String videoId;

  public static final String JSON_PROPERTY_VIDEO_PRESIGNED_URL = "video_presigned_url";
  @javax.annotation.Nullable
  private String videoPresignedUrl;

  public GithubComQeeqezApiInternalVideosHandlerUploadInitResponse() {
  }

  public GithubComQeeqezApiInternalVideosHandlerUploadInitResponse posterId(@javax.annotation.Nullable String posterId) {
    
    this.posterId = posterId;
    return this;
  }

  /**
   * Get posterId
   * @return posterId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_POSTER_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPosterId() {
    return posterId;
  }


  @JsonProperty(value = JSON_PROPERTY_POSTER_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPosterId(@javax.annotation.Nullable String posterId) {
    this.posterId = posterId;
  }

  public GithubComQeeqezApiInternalVideosHandlerUploadInitResponse posterPresignedUrl(@javax.annotation.Nullable String posterPresignedUrl) {
    
    this.posterPresignedUrl = posterPresignedUrl;
    return this;
  }

  /**
   * Get posterPresignedUrl
   * @return posterPresignedUrl
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_POSTER_PRESIGNED_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPosterPresignedUrl() {
    return posterPresignedUrl;
  }


  @JsonProperty(value = JSON_PROPERTY_POSTER_PRESIGNED_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPosterPresignedUrl(@javax.annotation.Nullable String posterPresignedUrl) {
    this.posterPresignedUrl = posterPresignedUrl;
  }

  public GithubComQeeqezApiInternalVideosHandlerUploadInitResponse uploadExpires(@javax.annotation.Nullable Integer uploadExpires) {
    
    this.uploadExpires = uploadExpires;
    return this;
  }

  /**
   * Get uploadExpires
   * @return uploadExpires
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_UPLOAD_EXPIRES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getUploadExpires() {
    return uploadExpires;
  }


  @JsonProperty(value = JSON_PROPERTY_UPLOAD_EXPIRES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUploadExpires(@javax.annotation.Nullable Integer uploadExpires) {
    this.uploadExpires = uploadExpires;
  }

  public GithubComQeeqezApiInternalVideosHandlerUploadInitResponse videoId(@javax.annotation.Nullable String videoId) {
    
    this.videoId = videoId;
    return this;
  }

  /**
   * Get videoId
   * @return videoId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VIDEO_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getVideoId() {
    return videoId;
  }


  @JsonProperty(value = JSON_PROPERTY_VIDEO_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVideoId(@javax.annotation.Nullable String videoId) {
    this.videoId = videoId;
  }

  public GithubComQeeqezApiInternalVideosHandlerUploadInitResponse videoPresignedUrl(@javax.annotation.Nullable String videoPresignedUrl) {
    
    this.videoPresignedUrl = videoPresignedUrl;
    return this;
  }

  /**
   * Get videoPresignedUrl
   * @return videoPresignedUrl
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VIDEO_PRESIGNED_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getVideoPresignedUrl() {
    return videoPresignedUrl;
  }


  @JsonProperty(value = JSON_PROPERTY_VIDEO_PRESIGNED_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVideoPresignedUrl(@javax.annotation.Nullable String videoPresignedUrl) {
    this.videoPresignedUrl = videoPresignedUrl;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GithubComQeeqezApiInternalVideosHandlerUploadInitResponse githubComQeeqezApiInternalVideosHandlerUploadInitResponse = (GithubComQeeqezApiInternalVideosHandlerUploadInitResponse) o;
    return Objects.equals(this.posterId, githubComQeeqezApiInternalVideosHandlerUploadInitResponse.posterId) &&
        Objects.equals(this.posterPresignedUrl, githubComQeeqezApiInternalVideosHandlerUploadInitResponse.posterPresignedUrl) &&
        Objects.equals(this.uploadExpires, githubComQeeqezApiInternalVideosHandlerUploadInitResponse.uploadExpires) &&
        Objects.equals(this.videoId, githubComQeeqezApiInternalVideosHandlerUploadInitResponse.videoId) &&
        Objects.equals(this.videoPresignedUrl, githubComQeeqezApiInternalVideosHandlerUploadInitResponse.videoPresignedUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(posterId, posterPresignedUrl, uploadExpires, videoId, videoPresignedUrl);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GithubComQeeqezApiInternalVideosHandlerUploadInitResponse {\n");
    sb.append("    posterId: ").append(toIndentedString(posterId)).append("\n");
    sb.append("    posterPresignedUrl: ").append(toIndentedString(posterPresignedUrl)).append("\n");
    sb.append("    uploadExpires: ").append(toIndentedString(uploadExpires)).append("\n");
    sb.append("    videoId: ").append(toIndentedString(videoId)).append("\n");
    sb.append("    videoPresignedUrl: ").append(toIndentedString(videoPresignedUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

