/*
 * RIXL API
 * **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@rixl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.rixl.sdk.videos.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * InternalImagesHandlerCompleteRequest
 */
@JsonPropertyOrder({
  InternalImagesHandlerCompleteRequest.JSON_PROPERTY_ATTACHED_TO_VIDEO,
  InternalImagesHandlerCompleteRequest.JSON_PROPERTY_IMAGE_ID
})
@JsonTypeName("internal_images_handler.completeRequest")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-23T11:10:33.968578+01:00[Africa/Lagos]", comments = "Generator version: 7.20.0")
public class InternalImagesHandlerCompleteRequest {
  public static final String JSON_PROPERTY_ATTACHED_TO_VIDEO = "attached_to_video";
  @javax.annotation.Nullable
  private Boolean attachedToVideo;

  public static final String JSON_PROPERTY_IMAGE_ID = "image_id";
  @javax.annotation.Nullable
  private String imageId;

  public InternalImagesHandlerCompleteRequest() {
  }

  public InternalImagesHandlerCompleteRequest attachedToVideo(@javax.annotation.Nullable Boolean attachedToVideo) {
    
    this.attachedToVideo = attachedToVideo;
    return this;
  }

  /**
   * Get attachedToVideo
   * @return attachedToVideo
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ATTACHED_TO_VIDEO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getAttachedToVideo() {
    return attachedToVideo;
  }


  @JsonProperty(value = JSON_PROPERTY_ATTACHED_TO_VIDEO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAttachedToVideo(@javax.annotation.Nullable Boolean attachedToVideo) {
    this.attachedToVideo = attachedToVideo;
  }

  public InternalImagesHandlerCompleteRequest imageId(@javax.annotation.Nullable String imageId) {
    
    this.imageId = imageId;
    return this;
  }

  /**
   * Get imageId
   * @return imageId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_IMAGE_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getImageId() {
    return imageId;
  }


  @JsonProperty(value = JSON_PROPERTY_IMAGE_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setImageId(@javax.annotation.Nullable String imageId) {
    this.imageId = imageId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InternalImagesHandlerCompleteRequest internalImagesHandlerCompleteRequest = (InternalImagesHandlerCompleteRequest) o;
    return Objects.equals(this.attachedToVideo, internalImagesHandlerCompleteRequest.attachedToVideo) &&
        Objects.equals(this.imageId, internalImagesHandlerCompleteRequest.imageId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(attachedToVideo, imageId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InternalImagesHandlerCompleteRequest {\n");
    sb.append("    attachedToVideo: ").append(toIndentedString(attachedToVideo)).append("\n");
    sb.append("    imageId: ").append(toIndentedString(imageId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

