/*
 * RIXL API
 * **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@rixl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.rixl.sdk.videos.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.rixl.sdk.videos.model.Image;
import io.rixl.sdk.videos.model.PaginationPagination;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * PaginationPaginatedResponseImage
 */
@JsonPropertyOrder({
  PaginationPaginatedResponseImage.JSON_PROPERTY_DATA,
  PaginationPaginatedResponseImage.JSON_PROPERTY_PAGINATION
})
@JsonTypeName("pagination.PaginatedResponse-Image")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-23T11:10:33.968578+01:00[Africa/Lagos]", comments = "Generator version: 7.20.0")
public class PaginationPaginatedResponseImage {
  public static final String JSON_PROPERTY_DATA = "data";
  @javax.annotation.Nullable
  private List<Image> data = new ArrayList<>();

  public static final String JSON_PROPERTY_PAGINATION = "pagination";
  @javax.annotation.Nullable
  private PaginationPagination pagination;

  public PaginationPaginatedResponseImage() {
  }

  public PaginationPaginatedResponseImage data(@javax.annotation.Nullable List<Image> data) {
    
    this.data = data;
    return this;
  }

  public PaginationPaginatedResponseImage addDataItem(Image dataItem) {
    if (this.data == null) {
      this.data = new ArrayList<>();
    }
    this.data.add(dataItem);
    return this;
  }

  /**
   * Data contains the slice of items for the current request.
   * @return data
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Image> getData() {
    return data;
  }


  @JsonProperty(value = JSON_PROPERTY_DATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setData(@javax.annotation.Nullable List<Image> data) {
    this.data = data;
  }

  public PaginationPaginatedResponseImage pagination(@javax.annotation.Nullable PaginationPagination pagination) {
    
    this.pagination = pagination;
    return this;
  }

  /**
   * Pagination data for the request.
   * @return pagination
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PAGINATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PaginationPagination getPagination() {
    return pagination;
  }


  @JsonProperty(value = JSON_PROPERTY_PAGINATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPagination(@javax.annotation.Nullable PaginationPagination pagination) {
    this.pagination = pagination;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaginationPaginatedResponseImage paginationPaginatedResponseImage = (PaginationPaginatedResponseImage) o;
    return Objects.equals(this.data, paginationPaginatedResponseImage.data) &&
        Objects.equals(this.pagination, paginationPaginatedResponseImage.pagination);
  }

  @Override
  public int hashCode() {
    return Objects.hash(data, pagination);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaginationPaginatedResponseImage {\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    pagination: ").append(toIndentedString(pagination)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

