/*
 * RIXL API
 * **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@rixl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.rixl.sdk.videos.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.rixl.sdk.videos.model.Chapter;
import io.rixl.sdk.videos.model.GithubComQeeqezApiDbSqlcPlanType;
import io.rixl.sdk.videos.model.Image;
import io.rixl.sdk.videos.model.ModelFile;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Video
 */
@JsonPropertyOrder({
  Video.JSON_PROPERTY_BITRATE,
  Video.JSON_PROPERTY_CHAPTERS,
  Video.JSON_PROPERTY_CODEC,
  Video.JSON_PROPERTY_DURATION,
  Video.JSON_PROPERTY_FILE,
  Video.JSON_PROPERTY_FRAMERATE,
  Video.JSON_PROPERTY_HDR,
  Video.JSON_PROPERTY_HEIGHT,
  Video.JSON_PROPERTY_ID,
  Video.JSON_PROPERTY_PLAN_TYPE,
  Video.JSON_PROPERTY_POSTER,
  Video.JSON_PROPERTY_WIDTH
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.20.0")
public class Video {
  public static final String JSON_PROPERTY_BITRATE = "bitrate";
  @javax.annotation.Nullable
  private Integer bitrate;

  public static final String JSON_PROPERTY_CHAPTERS = "chapters";
  @javax.annotation.Nullable
  private List<Chapter> chapters = new ArrayList<>();

  public static final String JSON_PROPERTY_CODEC = "codec";
  @javax.annotation.Nullable
  private String codec;

  public static final String JSON_PROPERTY_DURATION = "duration";
  @javax.annotation.Nullable
  private BigDecimal duration;

  public static final String JSON_PROPERTY_FILE = "file";
  @javax.annotation.Nullable
  private ModelFile _file;

  public static final String JSON_PROPERTY_FRAMERATE = "framerate";
  @javax.annotation.Nullable
  private String framerate;

  public static final String JSON_PROPERTY_HDR = "hdr";
  @javax.annotation.Nullable
  private Boolean hdr;

  public static final String JSON_PROPERTY_HEIGHT = "height";
  @javax.annotation.Nullable
  private Integer height;

  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nullable
  private String id;

  public static final String JSON_PROPERTY_PLAN_TYPE = "plan_type";
  @javax.annotation.Nullable
  private GithubComQeeqezApiDbSqlcPlanType planType;

  public static final String JSON_PROPERTY_POSTER = "poster";
  @javax.annotation.Nullable
  private Image poster;

  public static final String JSON_PROPERTY_WIDTH = "width";
  @javax.annotation.Nullable
  private Integer width;

  public Video() {
  }

  public Video bitrate(@javax.annotation.Nullable Integer bitrate) {
    
    this.bitrate = bitrate;
    return this;
  }

  /**
   * Get bitrate
   * @return bitrate
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BITRATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getBitrate() {
    return bitrate;
  }


  @JsonProperty(value = JSON_PROPERTY_BITRATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBitrate(@javax.annotation.Nullable Integer bitrate) {
    this.bitrate = bitrate;
  }

  public Video chapters(@javax.annotation.Nullable List<Chapter> chapters) {
    
    this.chapters = chapters;
    return this;
  }

  public Video addChaptersItem(Chapter chaptersItem) {
    if (this.chapters == null) {
      this.chapters = new ArrayList<>();
    }
    this.chapters.add(chaptersItem);
    return this;
  }

  /**
   * Get chapters
   * @return chapters
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CHAPTERS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Chapter> getChapters() {
    return chapters;
  }


  @JsonProperty(value = JSON_PROPERTY_CHAPTERS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setChapters(@javax.annotation.Nullable List<Chapter> chapters) {
    this.chapters = chapters;
  }

  public Video codec(@javax.annotation.Nullable String codec) {
    
    this.codec = codec;
    return this;
  }

  /**
   * Get codec
   * @return codec
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CODEC, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCodec() {
    return codec;
  }


  @JsonProperty(value = JSON_PROPERTY_CODEC, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCodec(@javax.annotation.Nullable String codec) {
    this.codec = codec;
  }

  public Video duration(@javax.annotation.Nullable BigDecimal duration) {
    
    this.duration = duration;
    return this;
  }

  /**
   * Get duration
   * @return duration
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DURATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getDuration() {
    return duration;
  }


  @JsonProperty(value = JSON_PROPERTY_DURATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDuration(@javax.annotation.Nullable BigDecimal duration) {
    this.duration = duration;
  }

  public Video _file(@javax.annotation.Nullable ModelFile _file) {
    
    this._file = _file;
    return this;
  }

  /**
   * Get _file
   * @return _file
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FILE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ModelFile getFile() {
    return _file;
  }


  @JsonProperty(value = JSON_PROPERTY_FILE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFile(@javax.annotation.Nullable ModelFile _file) {
    this._file = _file;
  }

  public Video framerate(@javax.annotation.Nullable String framerate) {
    
    this.framerate = framerate;
    return this;
  }

  /**
   * Get framerate
   * @return framerate
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FRAMERATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFramerate() {
    return framerate;
  }


  @JsonProperty(value = JSON_PROPERTY_FRAMERATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFramerate(@javax.annotation.Nullable String framerate) {
    this.framerate = framerate;
  }

  public Video hdr(@javax.annotation.Nullable Boolean hdr) {
    
    this.hdr = hdr;
    return this;
  }

  /**
   * Get hdr
   * @return hdr
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_HDR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getHdr() {
    return hdr;
  }


  @JsonProperty(value = JSON_PROPERTY_HDR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHdr(@javax.annotation.Nullable Boolean hdr) {
    this.hdr = hdr;
  }

  public Video height(@javax.annotation.Nullable Integer height) {
    
    this.height = height;
    return this;
  }

  /**
   * Get height
   * @return height
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_HEIGHT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getHeight() {
    return height;
  }


  @JsonProperty(value = JSON_PROPERTY_HEIGHT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHeight(@javax.annotation.Nullable Integer height) {
    this.height = height;
  }

  public Video id(@javax.annotation.Nullable String id) {
    
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@javax.annotation.Nullable String id) {
    this.id = id;
  }

  public Video planType(@javax.annotation.Nullable GithubComQeeqezApiDbSqlcPlanType planType) {
    
    this.planType = planType;
    return this;
  }

  /**
   * Get planType
   * @return planType
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PLAN_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GithubComQeeqezApiDbSqlcPlanType getPlanType() {
    return planType;
  }


  @JsonProperty(value = JSON_PROPERTY_PLAN_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPlanType(@javax.annotation.Nullable GithubComQeeqezApiDbSqlcPlanType planType) {
    this.planType = planType;
  }

  public Video poster(@javax.annotation.Nullable Image poster) {
    
    this.poster = poster;
    return this;
  }

  /**
   * Get poster
   * @return poster
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_POSTER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Image getPoster() {
    return poster;
  }


  @JsonProperty(value = JSON_PROPERTY_POSTER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPoster(@javax.annotation.Nullable Image poster) {
    this.poster = poster;
  }

  public Video width(@javax.annotation.Nullable Integer width) {
    
    this.width = width;
    return this;
  }

  /**
   * Get width
   * @return width
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_WIDTH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getWidth() {
    return width;
  }


  @JsonProperty(value = JSON_PROPERTY_WIDTH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWidth(@javax.annotation.Nullable Integer width) {
    this.width = width;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Video video = (Video) o;
    return Objects.equals(this.bitrate, video.bitrate) &&
        Objects.equals(this.chapters, video.chapters) &&
        Objects.equals(this.codec, video.codec) &&
        Objects.equals(this.duration, video.duration) &&
        Objects.equals(this._file, video._file) &&
        Objects.equals(this.framerate, video.framerate) &&
        Objects.equals(this.hdr, video.hdr) &&
        Objects.equals(this.height, video.height) &&
        Objects.equals(this.id, video.id) &&
        Objects.equals(this.planType, video.planType) &&
        Objects.equals(this.poster, video.poster) &&
        Objects.equals(this.width, video.width);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bitrate, chapters, codec, duration, _file, framerate, hdr, height, id, planType, poster, width);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Video {\n");
    sb.append("    bitrate: ").append(toIndentedString(bitrate)).append("\n");
    sb.append("    chapters: ").append(toIndentedString(chapters)).append("\n");
    sb.append("    codec: ").append(toIndentedString(codec)).append("\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("    _file: ").append(toIndentedString(_file)).append("\n");
    sb.append("    framerate: ").append(toIndentedString(framerate)).append("\n");
    sb.append("    hdr: ").append(toIndentedString(hdr)).append("\n");
    sb.append("    height: ").append(toIndentedString(height)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    planType: ").append(toIndentedString(planType)).append("\n");
    sb.append("    poster: ").append(toIndentedString(poster)).append("\n");
    sb.append("    width: ").append(toIndentedString(width)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

