/*
 * RIXL API
 * **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@rixl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.rixl.sdk.images.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.rixl.sdk.images.model.PaginationPagination;
import io.rixl.sdk.images.model.Post;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * PaginationPaginatedResponsePost
 */
@JsonPropertyOrder({
  PaginationPaginatedResponsePost.JSON_PROPERTY_DATA,
  PaginationPaginatedResponsePost.JSON_PROPERTY_PAGINATION
})
@JsonTypeName("pagination.PaginatedResponse-Post")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-23T11:10:36.106911+01:00[Africa/Lagos]", comments = "Generator version: 7.20.0")
public class PaginationPaginatedResponsePost {
  public static final String JSON_PROPERTY_DATA = "data";
  @javax.annotation.Nullable
  private List<Post> data = new ArrayList<>();

  public static final String JSON_PROPERTY_PAGINATION = "pagination";
  @javax.annotation.Nullable
  private PaginationPagination pagination;

  public PaginationPaginatedResponsePost() {
  }

  public PaginationPaginatedResponsePost data(@javax.annotation.Nullable List<Post> data) {
    
    this.data = data;
    return this;
  }

  public PaginationPaginatedResponsePost addDataItem(Post dataItem) {
    if (this.data == null) {
      this.data = new ArrayList<>();
    }
    this.data.add(dataItem);
    return this;
  }

  /**
   * Data contains the slice of items for the current request.
   * @return data
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Post> getData() {
    return data;
  }


  @JsonProperty(value = JSON_PROPERTY_DATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setData(@javax.annotation.Nullable List<Post> data) {
    this.data = data;
  }

  public PaginationPaginatedResponsePost pagination(@javax.annotation.Nullable PaginationPagination pagination) {
    
    this.pagination = pagination;
    return this;
  }

  /**
   * Pagination data for the request.
   * @return pagination
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PAGINATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PaginationPagination getPagination() {
    return pagination;
  }


  @JsonProperty(value = JSON_PROPERTY_PAGINATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPagination(@javax.annotation.Nullable PaginationPagination pagination) {
    this.pagination = pagination;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaginationPaginatedResponsePost paginationPaginatedResponsePost = (PaginationPaginatedResponsePost) o;
    return Objects.equals(this.data, paginationPaginatedResponsePost.data) &&
        Objects.equals(this.pagination, paginationPaginatedResponsePost.pagination);
  }

  @Override
  public int hashCode() {
    return Objects.hash(data, pagination);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaginationPaginatedResponsePost {\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    pagination: ").append(toIndentedString(pagination)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

