/*
 * RIXL API
 * **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@rixl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.rixl.sdk.images.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.rixl.sdk.images.model.GithubComQeeqezApiDbSqlcPlanType;
import io.rixl.sdk.images.model.GithubComQeeqezApiInternalVideosVideoResponse;
import io.rixl.sdk.images.model.Image;
import io.rixl.sdk.images.model.PostType;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Post
 */
@JsonPropertyOrder({
  Post.JSON_PROPERTY_CREATED_AT,
  Post.JSON_PROPERTY_CREATOR_ID,
  Post.JSON_PROPERTY_DESCRIPTION,
  Post.JSON_PROPERTY_FEED_ID,
  Post.JSON_PROPERTY_ID,
  Post.JSON_PROPERTY_IMAGE,
  Post.JSON_PROPERTY_PLAN_TYPE,
  Post.JSON_PROPERTY_TYPE,
  Post.JSON_PROPERTY_UPDATED_AT,
  Post.JSON_PROPERTY_VIDEO
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-23T11:10:36.106911+01:00[Africa/Lagos]", comments = "Generator version: 7.20.0")
public class Post {
  public static final String JSON_PROPERTY_CREATED_AT = "created_at";
  @javax.annotation.Nullable
  private String createdAt;

  public static final String JSON_PROPERTY_CREATOR_ID = "creator_id";
  @javax.annotation.Nullable
  private String creatorId;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @javax.annotation.Nullable
  private String description;

  public static final String JSON_PROPERTY_FEED_ID = "feed_id";
  @javax.annotation.Nullable
  private String feedId;

  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nullable
  private String id;

  public static final String JSON_PROPERTY_IMAGE = "image";
  @javax.annotation.Nullable
  private Image image;

  public static final String JSON_PROPERTY_PLAN_TYPE = "plan_type";
  @javax.annotation.Nullable
  private GithubComQeeqezApiDbSqlcPlanType planType;

  public static final String JSON_PROPERTY_TYPE = "type";
  @javax.annotation.Nullable
  private PostType type;

  public static final String JSON_PROPERTY_UPDATED_AT = "updated_at";
  @javax.annotation.Nullable
  private String updatedAt;

  public static final String JSON_PROPERTY_VIDEO = "video";
  @javax.annotation.Nullable
  private GithubComQeeqezApiInternalVideosVideoResponse video;

  public Post() {
  }

  public Post createdAt(@javax.annotation.Nullable String createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedAt(@javax.annotation.Nullable String createdAt) {
    this.createdAt = createdAt;
  }

  public Post creatorId(@javax.annotation.Nullable String creatorId) {
    
    this.creatorId = creatorId;
    return this;
  }

  /**
   * Get creatorId
   * @return creatorId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CREATOR_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCreatorId() {
    return creatorId;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATOR_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatorId(@javax.annotation.Nullable String creatorId) {
    this.creatorId = creatorId;
  }

  public Post description(@javax.annotation.Nullable String description) {
    
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }

  public Post feedId(@javax.annotation.Nullable String feedId) {
    
    this.feedId = feedId;
    return this;
  }

  /**
   * Get feedId
   * @return feedId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FEED_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFeedId() {
    return feedId;
  }


  @JsonProperty(value = JSON_PROPERTY_FEED_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFeedId(@javax.annotation.Nullable String feedId) {
    this.feedId = feedId;
  }

  public Post id(@javax.annotation.Nullable String id) {
    
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@javax.annotation.Nullable String id) {
    this.id = id;
  }

  public Post image(@javax.annotation.Nullable Image image) {
    
    this.image = image;
    return this;
  }

  /**
   * Get image
   * @return image
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_IMAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Image getImage() {
    return image;
  }


  @JsonProperty(value = JSON_PROPERTY_IMAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setImage(@javax.annotation.Nullable Image image) {
    this.image = image;
  }

  public Post planType(@javax.annotation.Nullable GithubComQeeqezApiDbSqlcPlanType planType) {
    
    this.planType = planType;
    return this;
  }

  /**
   * Get planType
   * @return planType
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PLAN_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GithubComQeeqezApiDbSqlcPlanType getPlanType() {
    return planType;
  }


  @JsonProperty(value = JSON_PROPERTY_PLAN_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPlanType(@javax.annotation.Nullable GithubComQeeqezApiDbSqlcPlanType planType) {
    this.planType = planType;
  }

  public Post type(@javax.annotation.Nullable PostType type) {
    
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PostType getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(@javax.annotation.Nullable PostType type) {
    this.type = type;
  }

  public Post updatedAt(@javax.annotation.Nullable String updatedAt) {
    
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * Get updatedAt
   * @return updatedAt
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_UPDATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUpdatedAt() {
    return updatedAt;
  }


  @JsonProperty(value = JSON_PROPERTY_UPDATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdatedAt(@javax.annotation.Nullable String updatedAt) {
    this.updatedAt = updatedAt;
  }

  public Post video(@javax.annotation.Nullable GithubComQeeqezApiInternalVideosVideoResponse video) {
    
    this.video = video;
    return this;
  }

  /**
   * Get video
   * @return video
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VIDEO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GithubComQeeqezApiInternalVideosVideoResponse getVideo() {
    return video;
  }


  @JsonProperty(value = JSON_PROPERTY_VIDEO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVideo(@javax.annotation.Nullable GithubComQeeqezApiInternalVideosVideoResponse video) {
    this.video = video;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Post post = (Post) o;
    return Objects.equals(this.createdAt, post.createdAt) &&
        Objects.equals(this.creatorId, post.creatorId) &&
        Objects.equals(this.description, post.description) &&
        Objects.equals(this.feedId, post.feedId) &&
        Objects.equals(this.id, post.id) &&
        Objects.equals(this.image, post.image) &&
        Objects.equals(this.planType, post.planType) &&
        Objects.equals(this.type, post.type) &&
        Objects.equals(this.updatedAt, post.updatedAt) &&
        Objects.equals(this.video, post.video);
  }

  @Override
  public int hashCode() {
    return Objects.hash(createdAt, creatorId, description, feedId, id, image, planType, type, updatedAt, video);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Post {\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    creatorId: ").append(toIndentedString(creatorId)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    feedId: ").append(toIndentedString(feedId)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    image: ").append(toIndentedString(image)).append("\n");
    sb.append("    planType: ").append(toIndentedString(planType)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    video: ").append(toIndentedString(video)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

