/*
 * RIXL API
 * **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@rixl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.rixl.sdk.images.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.rixl.sdk.images.model.GithubComQeeqezApiInternalVideosTypesChapterInput;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * UpdateChaptersRequest
 */
@JsonPropertyOrder({
  UpdateChaptersRequest.JSON_PROPERTY_CHAPTERS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-23T11:10:36.106911+01:00[Africa/Lagos]", comments = "Generator version: 7.20.0")
public class UpdateChaptersRequest {
  public static final String JSON_PROPERTY_CHAPTERS = "chapters";
  @javax.annotation.Nullable
  private List<GithubComQeeqezApiInternalVideosTypesChapterInput> chapters = new ArrayList<>();

  public UpdateChaptersRequest() {
  }

  public UpdateChaptersRequest chapters(@javax.annotation.Nullable List<GithubComQeeqezApiInternalVideosTypesChapterInput> chapters) {
    
    this.chapters = chapters;
    return this;
  }

  public UpdateChaptersRequest addChaptersItem(GithubComQeeqezApiInternalVideosTypesChapterInput chaptersItem) {
    if (this.chapters == null) {
      this.chapters = new ArrayList<>();
    }
    this.chapters.add(chaptersItem);
    return this;
  }

  /**
   * Get chapters
   * @return chapters
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CHAPTERS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<GithubComQeeqezApiInternalVideosTypesChapterInput> getChapters() {
    return chapters;
  }


  @JsonProperty(value = JSON_PROPERTY_CHAPTERS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setChapters(@javax.annotation.Nullable List<GithubComQeeqezApiInternalVideosTypesChapterInput> chapters) {
    this.chapters = chapters;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateChaptersRequest updateChaptersRequest = (UpdateChaptersRequest) o;
    return Objects.equals(this.chapters, updateChaptersRequest.chapters);
  }

  @Override
  public int hashCode() {
    return Objects.hash(chapters);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateChaptersRequest {\n");
    sb.append("    chapters: ").append(toIndentedString(chapters)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

