/*
 * RIXL API
 * **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@rixl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.rixl.sdk.images.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.rixl.sdk.images.model.GithubComQeeqezApiDbSqlcVideoQuality;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * VideoUploadInitRequest
 */
@JsonPropertyOrder({
  VideoUploadInitRequest.JSON_PROPERTY_FILE_NAME,
  VideoUploadInitRequest.JSON_PROPERTY_IMAGE_FORMAT,
  VideoUploadInitRequest.JSON_PROPERTY_VIDEO_QUALITY
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-23T11:10:36.106911+01:00[Africa/Lagos]", comments = "Generator version: 7.20.0")
public class VideoUploadInitRequest {
  public static final String JSON_PROPERTY_FILE_NAME = "file_name";
  @javax.annotation.Nonnull
  private String fileName;

  public static final String JSON_PROPERTY_IMAGE_FORMAT = "image_format";
  @javax.annotation.Nullable
  private String imageFormat;

  public static final String JSON_PROPERTY_VIDEO_QUALITY = "video_quality";
  @javax.annotation.Nullable
  private GithubComQeeqezApiDbSqlcVideoQuality videoQuality;

  public VideoUploadInitRequest() {
  }

  public VideoUploadInitRequest fileName(@javax.annotation.Nonnull String fileName) {
    
    this.fileName = fileName;
    return this;
  }

  /**
   * Get fileName
   * @return fileName
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_FILE_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getFileName() {
    return fileName;
  }


  @JsonProperty(value = JSON_PROPERTY_FILE_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFileName(@javax.annotation.Nonnull String fileName) {
    this.fileName = fileName;
  }

  public VideoUploadInitRequest imageFormat(@javax.annotation.Nullable String imageFormat) {
    
    this.imageFormat = imageFormat;
    return this;
  }

  /**
   * Get imageFormat
   * @return imageFormat
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_IMAGE_FORMAT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getImageFormat() {
    return imageFormat;
  }


  @JsonProperty(value = JSON_PROPERTY_IMAGE_FORMAT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setImageFormat(@javax.annotation.Nullable String imageFormat) {
    this.imageFormat = imageFormat;
  }

  public VideoUploadInitRequest videoQuality(@javax.annotation.Nullable GithubComQeeqezApiDbSqlcVideoQuality videoQuality) {
    
    this.videoQuality = videoQuality;
    return this;
  }

  /**
   * Get videoQuality
   * @return videoQuality
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VIDEO_QUALITY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GithubComQeeqezApiDbSqlcVideoQuality getVideoQuality() {
    return videoQuality;
  }


  @JsonProperty(value = JSON_PROPERTY_VIDEO_QUALITY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVideoQuality(@javax.annotation.Nullable GithubComQeeqezApiDbSqlcVideoQuality videoQuality) {
    this.videoQuality = videoQuality;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VideoUploadInitRequest videoUploadInitRequest = (VideoUploadInitRequest) o;
    return Objects.equals(this.fileName, videoUploadInitRequest.fileName) &&
        Objects.equals(this.imageFormat, videoUploadInitRequest.imageFormat) &&
        Objects.equals(this.videoQuality, videoUploadInitRequest.videoQuality);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fileName, imageFormat, videoQuality);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VideoUploadInitRequest {\n");
    sb.append("    fileName: ").append(toIndentedString(fileName)).append("\n");
    sb.append("    imageFormat: ").append(toIndentedString(imageFormat)).append("\n");
    sb.append("    videoQuality: ").append(toIndentedString(videoQuality)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

